Detailmodal
Foebry/auction_project pull request #40
Opened 2022-05-15 06:50 UTC by timvercammen

2022-05-15 07:16 UTC, Foebry commented on src/components/Auction.jsx
>  import { Routes } from "../types/RouteTypes";
Ongebruikte imports mogen nog weg

2022-05-15 07:17 UTC, Foebry commented on src/components/Auction.jsx
>          <>
Aangezien <article> hoofdelement is, worden geen "siblings" gerendered en mag de fragment (<></>) weggelaten worden

2022-05-15 07:21 UTC, Foebry commented on src/components/Routing.jsx
>          <Routes>
Ongebruikte routes mogen ook weg

2022-05-15 07:23 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
> +    const { state } = location;
wordt niet meer gebruikt

2022-05-15 07:25 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
> +                            {auctionDetail.biddings.map((bid) => (
bid kan je hier misschien nog destructeren

2022-05-15 07:27 UTC, Foebry commented on src/components/modals/LoginModal.jsx
> +                <Link to={Routes.REGISTER}>Register</Link>
Link zal niet meer werken. 
button met onClick setModal("register")

2022-05-15 07:29 UTC, Foebry commented on src/components/modals/RegisterModal.jsx
> +                <Link to={Routes.LOGIN}>Login</Link>
Zelfde als bij LoginModal

2022-05-15 07:32 UTC, Foebry commented on src/types/RouteTypes.js
>      INDEX: "/",
ongebruikte Routes mogen weggelaten worden

2022-05-15 07:33 UTC, Foebry requested changes
Overal nog eens nagaan om ongebruikte imports weg te halen

2022-05-16 11:05 UTC, Foebry approved these changes

2022-05-16 12:01 UTC, Michiel-Peeters approved these changes

2022-05-16 12:01 UTC, merged