Auction en Detailpagina met data
Foebry/auction_project pull request #46
Opened 2022-05-18 10:05 UTC by timvercammen

2022-05-18 10:46 UTC, Foebry commented on src/components/Auction.jsx
> +                )) || <p>no image</p>}
hier nog even een ander fallback image voorzien

2022-05-18 10:47 UTC, Foebry commented on src/components/Auction.jsx
> +                {name && (
check hier is niet nodig

2022-05-18 10:47 UTC, Foebry commented on src/components/Register.jsx
>  import { Routes } from "../types/RouteTypes";
Deze component wordt niet meer gebruikt en mag eigenlijk verwijdert worden

2022-05-18 10:48 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
>  const Detailblury__modal = ({ expiration }) => {
props mogen weggelaten worden

2022-05-18 10:49 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
> +    console.log("detail:", data);
console.log nog even weghalen

2022-05-18 10:50 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
> +                {data && data.name && <h2>{data.name}</h2>}{" "}
data && <h2>{data.name}</h2> moet volstaan

2022-05-18 10:52 UTC, Foebry commented on src/components/modals/Detailmodal.jsx
> +                                data.biddings.map((bid) => (
bid kan je misschien nog verder destructeren?

2022-05-18 10:53 UTC, Foebry commented on src/context/AppContext.jsx
> +    console.log({ modal });
mag nog weg

2022-05-18 10:58 UTC, Foebry commented on src/views/Index.jsx
> +                        {data.map(
Ok, maar kan korter tot `{data.map(auction=>(<Auction key={auction.id} {...auction} />))}`

2022-05-18 10:59 UTC, Foebry requested changes
Ziet er goed uit, nog enkele schoonheidsfoutjes wegwerken

2022-05-18 12:06 UTC, Foebry commented on src/components/Auction.jsx
> +                )) || (
dit alles kan nu wel iets eenvoudiger: `<img className="article__imgholder__img" src={img ?? "src/images/default.jpg"} />`

2022-05-18 12:26 UTC, Foebry commented on src/components/Auction.jsx
> +                    ></img>
met een onError kan je de src aanpasses moest deze niet (of foutief) meegegeven worden
`<img
                        className="article__imgholder__img"
                        src={image}
                        alt="#"
                        onError={({currentTarget}) =>
                            (currentTarget.src = "../src/images/default.jpg")
                        }
                    />`

2022-05-19 09:25 UTC, Foebry approved these changes

2022-05-19 11:31 UTC, Michiel-Peeters approved these changes

2022-05-19 11:32 UTC, merged